# This file specify the construction of multiple containers using Dockerfile with some general configuration with more broad scope
# In this example the services has no port exposed to host, the entry point should be through nginx witch has a loadbalance/reverse proxy configured
# The process of building the container and other essencial steps should be done in Dockerfile
#
# These containers share the same network and can reference each other as host by the service name
# In this example all services within this projects are being build, but they doesn't share any connection
# 
# Environment variables are set by a package(dotenv) in Express project, but they can be 'overriden' in this file
#
# Using an extra container from https://hub.docker.com/r/willfarrell/autoheal/ to perform automatic restart on unhealthy status
#

version: '3'
services:
    nginx-server:                                                               # nginx server that will serve as entry point for this compose project        
        image: esteveslima/nginx-server-image:latest
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:                                                             # set an order of dependency for starting/stopping services
            - base-js
            - base-ts
            - user-mongoose
        restart: always
        ports: 
            - "8080:80"
            - "8443:443"
    autoheal:                                                                   # useful package to restore unhealthy containers automatically        
        image: willfarrell/autoheal        
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
            - AUTOHEAL_INTERVAL=30
            - AUTOHEAL_START_PERIOD=15
        restart: always
    base-js:        
        image: esteveslima/base-js-image:latest                                 # tag image with username after build, enabling push to hub 
        build:
            context: ../templates/base-js
            dockerfile: Dockerfile
        deploy:
            replicas: 2                                                         # create replicas, require --compatibility flag to work without docker swarm
            restart_policy:
                condition: on-failure                                           # replaces restart policy
        environment:
            - LOGGING=false
        restart: always
    base-ts:        
        image: esteveslima/base-ts-image:latest                                    
        build:
            context: ../templates/base-ts
            dockerfile: Dockerfile
        deploy:
            replicas: 2                                                         # create replicas, require --compatibility flag to work without docker swarm
            restart_policy:
                condition: on-failure                                           # replaces restart policy
        environment:
            - LOGGING=false
        restart: always
    user-mongoose:        
        image: esteveslima/user-mongoose-image:latest                      
        build:
            context: ../templates/user-mongoose
            dockerfile: Dockerfile
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        depends_on:                                                             
            - mongo-database
        environment:
            - LOGGING=false
            - JWT_SECRET=userOverriden                                          # create env variable, which won't be replaced by dotenv node package
            - MONGO_URI=mongodb://mongo-database:27017/user-mongodb             # local database from mongodb container     
        restart: always                               
    mongo-database:                                                             # mongo container for local database option
        image: mongo
        volumes:
            - ../user-mongodb-storage:/data/db                                  # set a volume for database data
        environment:
            - MONGO_INITDB_DATABASE=user-mongodb                                # creates the databased used by user-mongoose container
            #- MONGO_INITDB_ROOT_USERNAME=user                                  # set auth credentials
            #- MONGO_INITDB_ROOT_PASSWORD=password
        restart: always
        expose:
            - '27017'                                                           # expose default mongodb port only for containers




            
# Possible useful definitions(currently may be not in use)
#
#   - env_file
#   - logging
#   - volumes: long syntax
#                 