sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_cb64ce276cc1_key -iv $encrypted_cb64ce276cc1_iv -in gcp-service-account.json.enc -out gcp-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcp-service-account.json
  - gcloud config set project proj-sd-280223
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials my-first-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: bash ./gke-deploy.sh
  on:
    branch: master
