apiVersion: v1
kind: Service                            
metadata:
  name: base-ts-cluster-ip-service  
spec:
  type: ClusterIP                        
  selector:
    component: base-ts             
  ports:
  - port: 8001                           
    targetPort: 8080                   
