apiVersion: extensions/v1beta1
kind: Ingress                                                       # allow access from outside(may take time to start)
metadata: 
  name: ingress-service                                             
  annotations:
    kubernetes.io/ingress.class: nginx                              # using nginx ingress from https://kubernetes.github.io/ingress-nginx/
    nginx.ingress.kubernetes.io/rewrite-target: /$2                 # removing the first part of the url path assigned below for routing
spec:
  rules:
    - http:
        paths: 
          - path: /base-js(/|$)(.*)                            # create a separate route for the service(which will be removed from url by rewrite-target)
            backend:
              serviceName: base-js-cluster-ip-service
              servicePort: 8000
          - path: /user-mongoose(/|$)(.*)
            backend:
              serviceName: user-mongoose-cluster-ip-service
              servicePort: 8001