apiVersion: v1
kind: Service
metadata:
  name: user-service-mongoose-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: user-service-mongoose
  ports:
  - port: 8001
    targetPort: 8080
