# This file specify the construction of multiple containers using Dockerfile with some general configuration
# The process of building the container and other essencial steps should be done in Dockerfile
#
# These containers share the same network and can reference each other as host by the service name
# In this example all services within this projects are being build, but they doesn't share any connection
# 
# Environment variables are set by a package(dotenv) in Express project, but they can be 'overriden' in this file
#
# Using an extra container from https://hub.docker.com/r/willfarrell/autoheal/ to perform automatic restart on unhealthy status
#

version: '3'
services:
    autoheal:
        restart: always
        image: willfarrell/autoheal
        environment:
          - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock    
    base-service:
        build:
            context: ./base-service
            dockerfile: Dockerfile
        environment:
            - LOGGING=false
        restart: always
        ports:
            - '8000:8080'
    user-service-mongoose:
        build:
            context: ./user-service-mongoose
            dockerfile: Dockerfile
        environment:
            - LOGGING=false
            - JWT_SECRET=userOverriden
            - MONGO_URI=mongodb+srv://esteveslima:q1w2e3r4t5y6@user-service-mongoose.1a696.mongodb.net/user-service-mongoose?retryWrites=true&w=majority
        restart: always
        ports:
            - '8001:8080'




            
# Possible useful definitions(currently may be not in use)
#
#   - build: network
#   - command
#   - depends_on
#   - deploy
#   - env_file
#   - logging
#   - volumes: long syntax
#                 