# Use the official image as a parent image.
FROM node:current as nodeBuilderStage

# Set the working directory.
WORKDIR /service

# Copy from your host to your current container location
COPY package.json .
# Run install command inside image filesystem.
RUN npm install

# Copy the rest of project files from your host to your current location.
COPY . .

# Checking container's health, using server status requisition inside the container
HEALTHCHECK --interval=5m --timeout=10s --start-period=10s --retries=5 CMD curl -f http://localhost:8080/status || exit 1

# Exposes ports to make them available for inter-container communication(external communication require publish)
EXPOSE 8080

# Run the specified command within the container.
CMD [ "npm", "run", "dev" ]



# Continue building image from the previous one if needed...
# FROM ...
# COPY --from=nodeBuilderStage <sourcePath> <targetPath>
# ...
