apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user-mongodb
  template:
    metadata:
      labels:
        component: user-mongodb
    spec:
      volumes:                                      # volume created in deployment made to allocate storage
        - name : user-mongodb-storage
          persistentVolumeClaim:
              claimName: user-mongodb-pvc   # pvc's name with the requirements for storage
      containers:
      - name: user-mongodb
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: user-mongodb-storage        # deployment volume that the container refers to
          mountPath: /data/db                       # directory with data to backup
        ports:
        - containerPort: 27017                      # default mongodb port
